# Generated by Django 3.1.5 on 2021-02-03 01:58

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_auto_20210201_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='movie_title',
            field=models.CharField(default=builtins.next, max_length=50),
            preserve_default=False,
        ),
    ]
