# Generated by Django 3.1.5 on 2021-02-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_favorites_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='movie_title',
        ),
    ]
